### ISSUE TITLE
Size of Social Media Links

### ISSUE THREAD

**Issue by emht** [pythonindia/inpycon2017#34]
I feel the size for the social media links are  very small and should be bigger than their present size.  

Because links to share must be highlighted.

**Comment by realslimshanky** [comment]
Hi @emht , Social links are looking good on the mobile view. They might look better if we scale them accordingly for the desktop view. Please go ahead and fix them if you like. Since the template is based of bootstrap make sure to use appropriate breakpoints as mentioned here in the [grid system](http://getbootstrap.com/css/#grid)

**Comment by shivakrishna9** [comment]
I will take this up! :)

**Comment by amoghj8** [comment]
Hey! I am thinking of modifying the font-sizes to 2em for screen sizes greater than or equal to 768px and 1.5em for less than 768px. Can I take up the issue?

**Comment by realslimshanky** [comment]
@shivakrishna9  sure, go ahead and make PR but please make sure you follow the guidelines stated [here](https://github.com/pythonindia/inpycon2017/blob/master/README.md)
@amoghj8, @shivakrishna9 started working on this issue before you, discuss the changes with him.

**Comment by realslimshanky** [comment]
@CuriousLearner we can close this issue. It has been fixed in #51
